[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[[deploy.environmentVariables]]
name = "SLACK_MCP_RATE_LIMIT"
value = "60"
